using System;

namespace Zipline.Client.Models;

/// <summary>
/// File metadata.
/// </summary>
public sealed class File
{
    /// <summary>
    /// File id.
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// File name (without extension).
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Original file name.
    /// </summary>
    public string? OriginalName { get; set; }

    /// <summary>
    /// MIME type.
    /// </summary>
    public string? Type { get; set; }

    /// <summary>
    /// File size in bytes.
    /// </summary>
    public long Size { get; set; }

    /// <summary>
    /// Number of views.
    /// </summary>
    public int Views { get; set; }

    /// <summary>
    /// Maximum view count.
    /// </summary>
    public int? MaxViews { get; set; }

    /// <summary>
    /// Whether the file is favorited.
    /// </summary>
    public bool Favorite { get; set; }

    /// <summary>
    /// Whether the file is password protected.
    /// </summary>
    public bool? Password { get; set; }

    /// <summary>
    /// Optional folder id.
    /// </summary>
    public string? FolderId { get; set; }

    /// <summary>
    /// Tags associated with the file.
    /// </summary>
    public Tag[]? Tags { get; set; }

    /// <summary>
    /// Optional thumbnail metadata.
    /// </summary>
    public FileThumbnail? Thumbnail { get; set; }

    /// <summary>
    /// Optional URL generated by server-side cleaners.
    /// </summary>
    public string? Url { get; set; }

    /// <summary>
    /// Creation timestamp.
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>
    /// Last update timestamp.
    /// </summary>
    public DateTimeOffset UpdatedAt { get; set; }

    /// <summary>
    /// Deletion timestamp if scheduled.
    /// </summary>
    public DateTimeOffset? DeletesAt { get; set; }
}

/// <summary>
/// Thumbnail metadata.
/// </summary>
public sealed class FileThumbnail
{
    /// <summary>
    /// Thumbnail path.
    /// </summary>
    public string? Path { get; set; }
}
